//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.12.08 at 04:13:42 PM GMT 
//


package ie.gmit.sw.Model;
import java.io.Serializable;
import java.util.Date;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="rentId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="custId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="carReg" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="date" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="numDays" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "rentId",
    "custId",
    "carReg",
    "date",
    "numDays"
})
@XmlRootElement(name = "Order")
public class Order implements Serializable{

	private static final long serialVersionUID = 1L;
    @XmlElement(required = true)
    protected String rentId;
    @XmlElement(required = true)
    protected String custId;
    @XmlElement(required = true)
    protected String carReg;
    @XmlElement(required = true)
    @XmlSchemaType(name = "date")
    protected Date date;
    protected int numDays;

    public Order() {
		super();
	}
    
    public Order(String rentId, String custId, String carReg, Date date, int numDays) {
    	super();
		this.rentId = rentId;
		this.custId = custId;
		this.carReg = carReg;
		this.date = date;
		this.numDays = numDays;
	}

	/**
     * Gets the value of the rentId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRentId() {
        return rentId;
    }

    /**
     * Sets the value of the rentId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRentId(String value) {
        this.rentId = value;
    }

    /**
     * Gets the value of the custId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustId() {
        return custId;
    }

    /**
     * Sets the value of the custId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustId(String value) {
        this.custId = value;
    }

    /**
     * Gets the value of the carReg property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCarReg() {
        return carReg;
    }

    /**
     * Sets the value of the carReg property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCarReg(String value) {
        this.carReg = value;
    }

    /**
     * Gets the value of the date property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public Date getDate() {
        return date;
    }

    /**
     * Sets the value of the date property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDate(Date value) {
        this.date = value;
    }

    /**
     * Gets the value of the numDays property.
     * 
     */
    public int getNumDays() {
        return numDays;
    }

    /**
     * Sets the value of the numDays property.
     * 
     */
    public void setNumDays(int value) {
        this.numDays = value;
    }

}
