//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.12.08 at 04:13:42 PM GMT 
//


package org.example.createorder;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="carReg" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="carMake" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="carModel" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "carReg",
    "carMake",
    "carModel"
})
@XmlRootElement(name = "Car")
public class Car {

    @XmlElement(required = true)
    protected String carReg;
    @XmlElement(required = true)
    protected String carMake;
    @XmlElement(required = true)
    protected String carModel;

    /**
     * Gets the value of the carReg property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCarReg() {
        return carReg;
    }

    /**
     * Sets the value of the carReg property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCarReg(String value) {
        this.carReg = value;
    }

    /**
     * Gets the value of the carMake property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCarMake() {
        return carMake;
    }

    /**
     * Sets the value of the carMake property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCarMake(String value) {
        this.carMake = value;
    }

    /**
     * Gets the value of the carModel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCarModel() {
        return carModel;
    }

    /**
     * Sets the value of the carModel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCarModel(String value) {
        this.carModel = value;
    }

}
